name: Blob storage login

on:
    push:
        branches: [ test_webapp ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPLE }}
